### ISSUE TITLE
In This index file setting Destination Data for one entity and set also its data in Txt file and mapping , the problem in another entities appeared empty and can exported

### ISSUE THREAD

**Issue by emannabil123** [emannabil123/repository01#5]
[IndexFile.xlsx](https://github.com/emannabil123/repository01/files/5763497/IndexFile.xlsx)
[invoice.txt](https://github.com/emannabil123/repository01/files/5763498/invoice.txt)

**Comment by MustafaE-ext** [comment]
txt is wrong structure, not a bug.
