### ISSUE TITLE
when try to map with SFTP for this files , invalid message appeared !!

### ISSUE THREAD

**Issue by emannabil123** [emannabil123/repository01#7]
[IndexFile.xlsx](https://github.com/emannabil123/repository01/files/5765121/IndexFile.xlsx)
[Stock_Card_NRF.txt](https://github.com/emannabil123/repository01/files/5765122/Stock_Card_NRF.txt)

![invalid path](https://user-images.githubusercontent.com/76688488/103543696-9f0f0a00-4ea7-11eb-8040-cc5a893b7657.PNG)

**Comment by MustafaE-ext** [comment]
not a bug
